// AUTO-GENERATED by scripts/gen-migrations.mjs — DO NOT EDIT.
// Regenerated on every build/deploy and typecheck. To add a migration, just
// drop a new NNNN_name.sql file into migrations/.
import m_0000_init_sql from "../../migrations/0000_init.sql";
import m_0001_phase4_sql from "../../migrations/0001_phase4.sql";
import m_0002_admin_notifications_sql from "../../migrations/0002_admin_notifications.sql";
import m_0003_blog_sql from "../../migrations/0003_blog.sql";
import m_0004_blog_seo_import_sql from "../../migrations/0004_blog_seo_import.sql";
import m_0005_admin_features_sql from "../../migrations/0005_admin_features.sql";
import m_0006_full_control_sql from "../../migrations/0006_full_control.sql";
import m_0007_deposits_sql from "../../migrations/0007_deposits.sql";
import m_0008_growth_safety_sql from "../../migrations/0008_growth_safety.sql";
import m_0009_payment_hardening_sql from "../../migrations/0009_payment_hardening.sql";
import m_0010_contest_banner_sql from "../../migrations/0010_contest_banner.sql";
import m_0011_voting_integrity_sql from "../../migrations/0011_voting_integrity.sql";

export interface Migration {
  name: string;
  sql: string;
}

export const MIGRATIONS: Migration[] = [
  { name: "0000_init.sql", sql: m_0000_init_sql },
  { name: "0001_phase4.sql", sql: m_0001_phase4_sql },
  { name: "0002_admin_notifications.sql", sql: m_0002_admin_notifications_sql },
  { name: "0003_blog.sql", sql: m_0003_blog_sql },
  { name: "0004_blog_seo_import.sql", sql: m_0004_blog_seo_import_sql },
  { name: "0005_admin_features.sql", sql: m_0005_admin_features_sql },
  { name: "0006_full_control.sql", sql: m_0006_full_control_sql },
  { name: "0007_deposits.sql", sql: m_0007_deposits_sql },
  { name: "0008_growth_safety.sql", sql: m_0008_growth_safety_sql },
  { name: "0009_payment_hardening.sql", sql: m_0009_payment_hardening_sql },
  { name: "0010_contest_banner.sql", sql: m_0010_contest_banner_sql },
  { name: "0011_voting_integrity.sql", sql: m_0011_voting_integrity_sql },
];
