// AUTO-GENERATED by scripts/gen-migrations.mjs — DO NOT EDIT.
// Regenerated on every build/deploy and typecheck. To add a migration, just
// drop a new NNNN_name.sql file into migrations/.
import m_0000_init_sql from "../../migrations/0000_init.sql";
import m_0001_phase4_sql from "../../migrations/0001_phase4.sql";
import m_0002_admin_notifications_sql from "../../migrations/0002_admin_notifications.sql";
import m_0003_blog_sql from "../../migrations/0003_blog.sql";
import m_0004_blog_seo_import_sql from "../../migrations/0004_blog_seo_import.sql";
import m_0005_admin_features_sql from "../../migrations/0005_admin_features.sql";
import m_0006_full_control_sql from "../../migrations/0006_full_control.sql";
import m_0007_deposits_sql from "../../migrations/0007_deposits.sql";
import m_0008_growth_safety_sql from "../../migrations/0008_growth_safety.sql";
import m_0009_payment_hardening_sql from "../../migrations/0009_payment_hardening.sql";
import m_0010_contest_banner_sql from "../../migrations/0010_contest_banner.sql";
import m_0011_voting_integrity_sql from "../../migrations/0011_voting_integrity.sql";
import m_0012_auth_unique_identifiers_sql from "../../migrations/0012_auth_unique_identifiers.sql";
import m_0013_error_logs_sql from "../../migrations/0013_error_logs.sql";
import m_0014_match_participant_index_sql from "../../migrations/0014_match_participant_index.sql";
import m_0015_follows_pagination_index_sql from "../../migrations/0015_follows_pagination_index.sql";
import m_0016_notifications_unread_index_sql from "../../migrations/0016_notifications_unread_index.sql";
import m_0017_bunny_video_sql from "../../migrations/0017_bunny_video.sql";
import m_0018_notifications_production_sql from "../../migrations/0018_notifications_production.sql";
import m_0019_notification_seen_index_sql from "../../migrations/0019_notification_seen_index.sql";
import m_0020_deposit_package_sql from "../../migrations/0020_deposit_package.sql";
import m_0021_bonus_coin_breakdown_sql from "../../migrations/0021_bonus_coin_breakdown.sql";
import m_0022_hot_path_indexes_sql from "../../migrations/0022_hot_path_indexes.sql";
import m_0023_money_integrity_sql from "../../migrations/0023_money_integrity.sql";
import m_0024_payment_lifecycle_sql from "../../migrations/0024_payment_lifecycle.sql";
import m_0025_ops_heartbeat_sql from "../../migrations/0025_ops_heartbeat.sql";

export interface Migration {
  name: string;
  sql: string;
}

export const MIGRATIONS: Migration[] = [
  { name: "0000_init.sql", sql: m_0000_init_sql },
  { name: "0001_phase4.sql", sql: m_0001_phase4_sql },
  { name: "0002_admin_notifications.sql", sql: m_0002_admin_notifications_sql },
  { name: "0003_blog.sql", sql: m_0003_blog_sql },
  { name: "0004_blog_seo_import.sql", sql: m_0004_blog_seo_import_sql },
  { name: "0005_admin_features.sql", sql: m_0005_admin_features_sql },
  { name: "0006_full_control.sql", sql: m_0006_full_control_sql },
  { name: "0007_deposits.sql", sql: m_0007_deposits_sql },
  { name: "0008_growth_safety.sql", sql: m_0008_growth_safety_sql },
  { name: "0009_payment_hardening.sql", sql: m_0009_payment_hardening_sql },
  { name: "0010_contest_banner.sql", sql: m_0010_contest_banner_sql },
  { name: "0011_voting_integrity.sql", sql: m_0011_voting_integrity_sql },
  { name: "0012_auth_unique_identifiers.sql", sql: m_0012_auth_unique_identifiers_sql },
  { name: "0013_error_logs.sql", sql: m_0013_error_logs_sql },
  { name: "0014_match_participant_index.sql", sql: m_0014_match_participant_index_sql },
  { name: "0015_follows_pagination_index.sql", sql: m_0015_follows_pagination_index_sql },
  { name: "0016_notifications_unread_index.sql", sql: m_0016_notifications_unread_index_sql },
  { name: "0017_bunny_video.sql", sql: m_0017_bunny_video_sql },
  { name: "0018_notifications_production.sql", sql: m_0018_notifications_production_sql },
  { name: "0019_notification_seen_index.sql", sql: m_0019_notification_seen_index_sql },
  { name: "0020_deposit_package.sql", sql: m_0020_deposit_package_sql },
  { name: "0021_bonus_coin_breakdown.sql", sql: m_0021_bonus_coin_breakdown_sql },
  { name: "0022_hot_path_indexes.sql", sql: m_0022_hot_path_indexes_sql },
  { name: "0023_money_integrity.sql", sql: m_0023_money_integrity_sql },
  { name: "0024_payment_lifecycle.sql", sql: m_0024_payment_lifecycle_sql },
  { name: "0025_ops_heartbeat.sql", sql: m_0025_ops_heartbeat_sql },
];
