/**
 * SEO audit engine.
 *
 * Produces a scored, severity-ranked report across eight SEO categories from two
 * sources ONLY: our own D1 content, and live HTTP probes of our own public site.
 *
 * ---------------------------------------------------------------------------
 * What this deliberately does NOT do
 * ---------------------------------------------------------------------------
 * Three categories cannot be measured from anything this deployment owns, and
 * each is reported as `not_configured` with the credential it needs rather than
 * given an invented number:
 *
 *  - OFF-PAGE (backlinks, referring domains, anchor text, domain authority,
 *    toxic-link detection). This requires a crawl index we do not have. There is
 *    no honest way to synthesise it, and a dashboard showing a made-up
 *    "Domain Authority: 34/100" is worse than an empty panel: someone will make
 *    a decision on it. Needs Search Console, or an Ahrefs/Moz/Semrush key.
 *  - PAGE SPEED / CORE WEB VITALS. Real Core Web Vitals are FIELD data from
 *    actual visitors. A Worker cannot measure them. Needs the PageSpeed Insights
 *    API (free key) or the CrUX API.
 *  - KEYWORD RESEARCH / SEARCH VOLUME / SEARCH INTENT scoring. Volume and
 *    competition come from a keyword provider; intent classification without
 *    query data is guesswork dressed as analysis.
 *
 * LOCAL SEO is scored only on the parts that genuinely apply to this product (an
 * India-focused *online* contest platform): language signals and organisation
 * contact data. It deliberately does NOT check for or recommend per-city landing
 * pages — see `LOCAL_NOTE`. That is not an omission, it is the same rule the
 * brief itself sets out under "avoid doorway pages".
 *
 * Every issue carries a deterministic `suggestion` where one can be derived from
 * the data (a truncated title, a description built from the excerpt). No text is
 * generated by a language model, so nothing here can hallucinate a fix.
 */
import { and, eq, sql } from "drizzle-orm";
import type { Env } from "../types";
import { getDb, schema } from "../db";

// ---------------------------------------------------------------------------
// Model
// ---------------------------------------------------------------------------

export type Severity = "critical" | "high" | "medium" | "low";

export type CategoryId =
  | "technical"
  | "onPage"
  | "programmatic"
  | "content"
  | "offPage"
  | "local"
  | "image"
  | "aiSearch";

export interface SeoIssue {
  /** Stable id, so a fix can be verified against the next run. */
  id: string;
  category: CategoryId;
  severity: Severity;
  title: string;
  /** Why it matters — the consequence, not a restatement of the title. */
  detail: string;
  /** Sample of affected urls/slugs, capped. `affectedCount` is the real total. */
  affected: string[];
  affectedCount: number;
  /** Deterministic, reviewable fix. Never model-generated. */
  suggestion?: string;
}

export interface PassedCheck {
  id: string;
  category: CategoryId;
  title: string;
}

export type CategoryStatus = "ok" | "warn" | "fail" | "not_configured";

export interface CategoryScore {
  id: CategoryId;
  label: string;
  /** null when the category cannot be measured — never a guessed number. */
  score: number | null;
  status: CategoryStatus;
  checksRun: number;
  checksPassed: number;
  /** Present when score is null: what is missing and how to enable it. */
  note?: string;
}

export interface SeoAudit {
  ranAt: number;
  durationMs: number;
  origin: string;
  /** Mean of the measurable categories only. */
  overall: number | null;
  categories: CategoryScore[];
  issues: SeoIssue[];
  passed: PassedCheck[];
  totals: Record<Severity, number>;
  /** Content counted, for context on the numbers above. */
  scope: { posts: number; publicRoutes: number; probes: number };
}

const CATEGORY_LABELS: Record<CategoryId, string> = {
  technical: "Technical SEO",
  onPage: "On-Page SEO",
  programmatic: "Programmatic SEO",
  content: "Content SEO",
  offPage: "Off-Page SEO",
  local: "Local SEO",
  image: "Image SEO",
  aiSearch: "AI Search / GEO",
};

/**
 * Score deductions per failing check.
 *
 * A category starts at 100 and loses this much per failing check. The weights are
 * ordered so that one critical failure alone cannot leave a category looking
 * healthy, while a handful of `low` findings cannot tank it either.
 */
const SEVERITY_WEIGHT: Record<Severity, number> = {
  critical: 30,
  high: 14,
  medium: 7,
  low: 2,
};

/** Sample size for issue lists. The full count is always reported separately. */
const SAMPLE = 8;

const NOT_CONFIGURED: Partial<Record<CategoryId, string>> = {
  offPage:
    "Needs an external backlink data source — Google Search Console, or an Ahrefs / Moz / Semrush API key. " +
    "Backlinks, referring domains, anchor text and domain authority cannot be observed from this deployment, " +
    "and this panel will not display an estimated figure in their place.",
};

const LOCAL_NOTE =
  "Scored on the signals that apply to a national online platform: page language and organisation contact data. " +
  "Per-city landing pages are intentionally not implemented or recommended: TopHunt has no per-city inventory, " +
  "service area or address, so city pages would be near-duplicate doorway pages — which the SEO policy for this " +
  "project explicitly rules out. LocalBusiness schema is likewise not applicable (no physical premises).";

// ---------------------------------------------------------------------------
// Collector
// ---------------------------------------------------------------------------

class Report {
  issues: SeoIssue[] = [];
  passed: PassedCheck[] = [];
  private run = new Map<CategoryId, number>();
  private ok = new Map<CategoryId, number>();

  /**
   * Record one check. `affected` empty ⇒ the check passed.
   *
   * Both outcomes are recorded, because a dashboard that only lists problems
   * cannot distinguish "healthy" from "never looked".
   */
  check(
    category: CategoryId,
    id: string,
    severity: Severity,
    title: string,
    detail: string,
    affected: string[],
    affectedCount = affected.length,
    suggestion?: string,
  ): void {
    this.run.set(category, (this.run.get(category) ?? 0) + 1);
    if (affectedCount === 0) {
      this.ok.set(category, (this.ok.get(category) ?? 0) + 1);
      this.passed.push({ id, category, title });
      return;
    }
    this.issues.push({
      id,
      category,
      severity,
      title,
      detail,
      affected: affected.slice(0, SAMPLE),
      affectedCount,
      suggestion,
    });
  }

  score(category: CategoryId): CategoryScore {
    const note = NOT_CONFIGURED[category] ?? (category === "local" ? LOCAL_NOTE : undefined);
    const checksRun = this.run.get(category) ?? 0;
    if (checksRun === 0) {
      return {
        id: category,
        label: CATEGORY_LABELS[category],
        score: null,
        status: "not_configured",
        checksRun: 0,
        checksPassed: 0,
        note: note ?? "No checks available for this category.",
      };
    }
    const deduction = this.issues
      .filter((i) => i.category === category)
      .reduce((sum, i) => sum + SEVERITY_WEIGHT[i.severity], 0);
    const score = Math.max(0, Math.min(100, 100 - deduction));
    const worst = this.issues.filter((i) => i.category === category);
    const status: CategoryStatus = worst.some((i) => i.severity === "critical")
      ? "fail"
      : score < 70
        ? "fail"
        : score < 90
          ? "warn"
          : "ok";
    return {
      id: category,
      label: CATEGORY_LABELS[category],
      score,
      status,
      checksRun,
      checksPassed: this.ok.get(category) ?? 0,
      ...(category === "local" ? { note } : {}),
    };
  }
}

// ---------------------------------------------------------------------------
// Helpers over post content
// ---------------------------------------------------------------------------

const stripTags = (html: string) =>
  String(html || "")
    .replace(/<script[\s\S]*?<\/script>/gi, " ")
    .replace(/<style[\s\S]*?<\/style>/gi, " ")
    .replace(/<[^>]+>/g, " ")
    .replace(/\s+/g, " ")
    .trim();

const wordCount = (html: string) => (stripTags(html).match(/\S+/g) || []).length;

/** `<img>` tags with no non-empty alt attribute. */
function imagesMissingAlt(html: string): number {
  const imgs = String(html || "").match(/<img\b[^>]*>/gi) || [];
  return imgs.filter((tag) => {
    const alt = tag.match(/\balt\s*=\s*("([^"]*)"|'([^']*)')/i);
    return !alt || !(alt[2] || alt[3] || "").trim();
  }).length;
}

/** Anything that points back at this site — the internal-link signal. */
function internalLinkCount(html: string, hostname: string): number {
  const hrefs = [...String(html || "").matchAll(/<a\b[^>]*href\s*=\s*"([^"]+)"/gi)].map((m) => m[1]);
  return hrefs.filter((h) => h.startsWith("/") || h.includes(hostname)).length;
}

const headingLevels = (html: string) =>
  [...String(html || "").matchAll(/<h([1-6])\b/gi)].map((m) => Number(m[1]));

/** Does the post read like a Q&A? Only then is FAQPage schema honest. */
function looksLikeFaq(html: string): boolean {
  const text = stripTags(html);
  const questionHeadings = [...String(html || "").matchAll(/<h[2-4]\b[^>]*>([\s\S]*?)<\/h[2-4]>/gi)]
    .map((m) => stripTags(m[1]))
    .filter((h) => /\?$/.test(h.trim()) || /^(what|how|why|when|where|which|who|is|are|can|does|do)\b/i.test(h.trim()));
  return questionHeadings.length >= 2 || (text.match(/\?/g) || []).length >= 4;
}

const isKebabSlug = (slug: string) => /^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug);

// ---------------------------------------------------------------------------
// Live probes of our own public site
// ---------------------------------------------------------------------------

interface Probe {
  path: string;
  status: number;
  contentType: string;
  body: string;
  ok: boolean;
}

/**
 * Fetch one of our own pages.
 *
 * `Accept: text/html` matters: the SEO Worker only rewrites the document for HTML
 * navigations, so a probe without it measures the raw shell and every on-page
 * check would report a false failure.
 */
async function probe(origin: string, path: string, accept = "text/html"): Promise<Probe> {
  try {
    const res = await fetch(`${origin}${path}`, {
      headers: { accept, "user-agent": "TopHuntSeoAudit/1.0" },
      redirect: "follow",
    });
    const body = await res.text();
    return {
      path,
      status: res.status,
      contentType: res.headers.get("content-type") || "",
      body,
      ok: res.ok,
    };
  } catch (e) {
    return { path, status: 0, contentType: "", body: "", ok: false };
  }
}

const metaContent = (html: string, attr: "name" | "property", key: string): string | null => {
  const re = new RegExp(`<meta[^>]*${attr}=["']${key}["'][^>]*content=["']([^"']*)["']`, "i");
  const alt = new RegExp(`<meta[^>]*content=["']([^"']*)["'][^>]*${attr}=["']${key}["']`, "i");
  return (html.match(re) || html.match(alt) || [])[1] ?? null;
};

const titleOf = (html: string) => (html.match(/<title>([^<]*)<\/title>/i) || [])[1] ?? null;
const canonicalOf = (html: string) =>
  (html.match(/<link[^>]*rel=["']canonical["'][^>]*href=["']([^"']+)["']/i) || [])[1] ?? null;
const hasJsonLdType = (html: string, type: string) =>
  new RegExp(`"@type"\\s*:\\s*"${type}"`).test(html);

// ---------------------------------------------------------------------------
// The audit
// ---------------------------------------------------------------------------

/** Public routes the SEO Worker advertises. Kept in step with PUBLIC_ROUTES there. */
export const AUDITED_PUBLIC_ROUTES = [
  "/",
  "/home",
  "/explore",
  "/explore/leaderboard",
  "/blog",
  "/legal/privacy",
  "/legal/terms",
  "/legal/refund",
  "/legal/guidelines",
] as const;

/** A sample of screens that must never be indexable. */
const AUDITED_PRIVATE_ROUTES = ["/wallet/withdraw", "/auth/login", "/setting"] as const;

export function seoSiteOrigin(env: Env): string {
  const configured = String((env as any).SEO_SITE_ORIGIN || "").trim();
  return (configured || "https://tophunt.in").replace(/\/$/, "");
}

export async function runSeoAudit(env: Env): Promise<SeoAudit> {
  const startedAt = Date.now();
  const origin = seoSiteOrigin(env);
  const hostname = new URL(origin).hostname;
  const r = new Report();

  const db = getDb(env);
  const posts = await db
    .select({
      slug: schema.blogPosts.slug,
      title: schema.blogPosts.title,
      metaTitle: schema.blogPosts.metaTitle,
      metaDescription: schema.blogPosts.metaDescription,
      excerpt: schema.blogPosts.excerpt,
      content: schema.blogPosts.content,
      coverImageUrl: schema.blogPosts.coverImageUrl,
      canonicalUrl: schema.blogPosts.canonicalUrl,
      author: schema.blogPosts.author,
      category: schema.blogPosts.category,
      publishedAt: schema.blogPosts.publishedAt,
      updatedAt: schema.blogPosts.updatedAt,
    })
    .from(schema.blogPosts)
    .where(eq(schema.blogPosts.status, "published"))
    .all();

  // ---- live probes (bounded: this runs inside one Worker invocation) --------
  const routeProbes = await Promise.all(
    AUDITED_PUBLIC_ROUTES.map((p) => probe(origin, p)),
  );
  const privateProbes = await Promise.all(AUDITED_PRIVATE_ROUTES.map((p) => probe(origin, p)));
  const [robots, sitemap, notFound, samplePost] = await Promise.all([
    probe(origin, "/robots.txt", "text/plain"),
    probe(origin, "/sitemap.xml", "application/xml"),
    probe(origin, "/this-path-should-not-exist-seo-audit", "text/html"),
    posts.length ? probe(origin, `/blog/${posts[0].slug}`) : Promise.resolve(null as any),
  ]);
  const probeCount = routeProbes.length + privateProbes.length + 3 + (samplePost ? 1 : 0);

  runTechnical(r, { origin, robots, sitemap, notFound, routeProbes, privateProbes, posts });
  runOnPage(r, { origin, hostname, posts, routeProbes, samplePost });
  runProgrammatic(r, { posts, samplePost });
  runContent(r, { posts });
  runImage(r, { posts });
  runAiSearch(r, { posts, routeProbes, samplePost });
  runLocal(r, { routeProbes });

  // Off-page has no data source. One explicit, honest entry — no checks, no score.
  const categories: CategoryScore[] = (
    ["technical", "onPage", "programmatic", "content", "offPage", "local", "image", "aiSearch"] as CategoryId[]
  ).map((id) => r.score(id));

  const measurable = categories.filter((c) => c.score !== null).map((c) => c.score as number);
  const overall = measurable.length
    ? Math.round(measurable.reduce((a, b) => a + b, 0) / measurable.length)
    : null;

  const totals: Record<Severity, number> = { critical: 0, high: 0, medium: 0, low: 0 };
  for (const i of r.issues) totals[i.severity] += 1;

  const severityOrder: Severity[] = ["critical", "high", "medium", "low"];
  r.issues.sort(
    (a, b) =>
      severityOrder.indexOf(a.severity) - severityOrder.indexOf(b.severity) ||
      b.affectedCount - a.affectedCount,
  );

  return {
    ranAt: startedAt,
    durationMs: Date.now() - startedAt,
    origin,
    overall,
    categories,
    issues: r.issues,
    passed: r.passed,
    totals,
    scope: { posts: posts.length, publicRoutes: AUDITED_PUBLIC_ROUTES.length, probes: probeCount },
  };
}

// ---------------------------------------------------------------------------
// Category: Technical
// ---------------------------------------------------------------------------

function runTechnical(
  r: Report,
  x: {
    origin: string;
    robots: Probe;
    sitemap: Probe;
    notFound: Probe;
    routeProbes: Probe[];
    privateProbes: Probe[];
    posts: any[];
  },
): void {
  const { origin, robots, sitemap, notFound, routeProbes, privateProbes, posts } = x;

  r.check(
    "technical",
    "tech.https",
    "critical",
    "Site is served over HTTPS",
    "Search engines demote plain HTTP, and the app handles logins and payments.",
    origin.startsWith("https://") ? [] : [origin],
  );

  r.check(
    "technical",
    "tech.robots.reachable",
    "high",
    "robots.txt is reachable",
    "Without it crawlers apply their own defaults and cannot discover the sitemap.",
    robots.ok ? [] : ["/robots.txt"],
  );

  // Our robots.txt always advertises the sitemap. If the served one does not, it
  // is not ours — Cloudflare's managed robots.txt (AI crawl control) replaces the
  // whole file at the edge, and that is invisible from the codebase.
  const robotsIsOurs = robots.body.includes(`Sitemap: ${origin}/sitemap.xml`);
  r.check(
    "technical",
    "tech.robots.sitemap",
    "high",
    "robots.txt points at the sitemap",
    "The served robots.txt does not reference our sitemap, so crawlers will not find it there. " +
      "A managed robots.txt at the zone level (Cloudflare AI crawl control) overrides the app's own file.",
    robotsIsOurs ? [] : ["/robots.txt"],
    robotsIsOurs ? 0 : 1,
    robotsIsOurs
      ? undefined
      : "Disable the managed/AI-crawl robots.txt on the tophunt.in zone so the app's robots.txt is served, " +
        "then submit the sitemap in Search Console.",
  );

  const sitemapIsXml = sitemap.contentType.includes("xml");
  r.check(
    "technical",
    "tech.sitemap.xml",
    "critical",
    "sitemap.xml is served as XML",
    "An HTML response at /sitemap.xml means the SEO edge Worker is not running and no URLs are being submitted.",
    sitemapIsXml ? [] : ["/sitemap.xml"],
  );

  const sitemapUrls = (sitemap.body.match(/<url>/g) || []).length;
  const expected = posts.length + AUDITED_PUBLIC_ROUTES.length;
  // 2% tolerance: a post published between the sitemap's cache fill and this run
  // is not a defect.
  const shortfall = expected - sitemapUrls;
  r.check(
    "technical",
    "tech.sitemap.complete",
    "high",
    "sitemap.xml lists every public URL",
    `The sitemap holds ${sitemapUrls} URLs but ${expected} are expected (${posts.length} posts + ${AUDITED_PUBLIC_ROUTES.length} routes). ` +
      "Missing URLs are simply never advertised to search engines.",
    sitemapIsXml && shortfall > Math.ceil(expected * 0.02) ? [`${shortfall} URLs missing`] : [],
    sitemapIsXml && shortfall > Math.ceil(expected * 0.02) ? shortfall : 0,
  );

  r.check(
    "technical",
    "tech.sitemap.incomplete_flag",
    "medium",
    "sitemap.xml is not flagged incomplete",
    "The generator marks a sitemap it knows to be truncated. That marker is present.",
    sitemap.body.includes("INCOMPLETE") ? ["/sitemap.xml"] : [],
  );

  const noCanonical = routeProbes.filter((p) => p.ok && !canonicalOf(p.body)).map((p) => p.path);
  r.check(
    "technical",
    "tech.canonical.present",
    "high",
    "Every public route declares a canonical URL",
    "Without one, query strings and trailing-slash variants compete as separate pages.",
    noCanonical,
  );

  const wrongCanonical = routeProbes
    .filter((p) => {
      const c = canonicalOf(p.body);
      if (!c) return false;
      try {
        return new URL(c).origin !== origin;
      } catch {
        return true;
      }
    })
    .map((p) => p.path);
  r.check(
    "technical",
    "tech.canonical.origin",
    "critical",
    "Canonical URLs point at this site",
    "A canonical on another origin tells search engines to rank that site instead of this one.",
    wrongCanonical,
  );

  const indexablePrivate = privateProbes
    .filter((p) => {
      const robotsMeta = metaContent(p.body, "name", "robots") || "";
      return !robotsMeta.includes("noindex");
    })
    .map((p) => p.path);
  r.check(
    "technical",
    "tech.noindex.private",
    "critical",
    "Signed-in and transactional screens are noindex",
    "Wallet, auth and settings screens must not be indexable. An indexed withdrawal or OTP screen is a " +
      "privacy and trust problem, not just an SEO one.",
    indexablePrivate,
  );

  const notFoundRobots = metaContent(notFound.body, "name", "robots") || "";
  r.check(
    "technical",
    "tech.404.noindex",
    "medium",
    "Unknown paths are not indexable",
    "This SPA answers every path with 200, so a typo'd URL becomes an indexable duplicate of the shell " +
      "unless it is explicitly marked noindex.",
    notFoundRobots.includes("noindex") ? [] : [notFound.path],
  );

  const brokenRoutes = routeProbes.filter((p) => !p.ok).map((p) => `${p.path} → ${p.status || "network error"}`);
  r.check(
    "technical",
    "tech.routes.reachable",
    "critical",
    "Every advertised public route responds",
    "A route in the sitemap that does not respond wastes crawl budget and can be dropped from the index.",
    brokenRoutes,
  );
}

// ---------------------------------------------------------------------------
// Category: On-Page
// ---------------------------------------------------------------------------

function runOnPage(
  r: Report,
  x: { origin: string; hostname: string; posts: any[]; routeProbes: Probe[]; samplePost: Probe | null },
): void {
  const { hostname, posts, routeProbes, samplePost } = x;

  // --- rendered routes ---
  const missingTitle = routeProbes.filter((p) => p.ok && !titleOf(p.body)).map((p) => p.path);
  r.check("onPage", "onpage.route.title", "critical", "Every public route has a <title>", "A page with no title cannot rank for anything.", missingTitle);

  const missingDesc = routeProbes.filter((p) => p.ok && !metaContent(p.body, "name", "description")).map((p) => p.path);
  r.check(
    "onPage",
    "onpage.route.description",
    "high",
    "Every public route has a meta description",
    "Without one the search snippet is scraped from arbitrary page text, and click-through suffers.",
    missingDesc,
  );

  const missingOg = routeProbes
    .filter((p) => p.ok && !metaContent(p.body, "property", "og:title"))
    .map((p) => p.path);
  r.check(
    "onPage",
    "onpage.route.og",
    "medium",
    "Every public route has Open Graph tags",
    "WhatsApp, Facebook and Telegram do not execute JavaScript; without server-rendered OG tags a shared " +
      "link unfurls as a bare URL.",
    missingOg,
  );

  const missingTwitter = routeProbes
    .filter((p) => p.ok && !metaContent(p.body, "name", "twitter:card"))
    .map((p) => p.path);
  r.check("onPage", "onpage.route.twitter", "low", "Every public route has a Twitter card", "Controls how the link renders on X.", missingTwitter);

  // --- stored post metadata ---
  const longTitles = posts
    .filter((p) => (p.metaTitle || p.title || "").length > 65)
    .map((p) => `${p.slug} (${(p.metaTitle || p.title).length} chars)`);
  r.check(
    "onPage",
    "onpage.post.title_length",
    "low",
    "Post titles fit a search result",
    "Titles beyond ~65 characters are truncated with an ellipsis in Google, hiding the end of the headline.",
    longTitles,
    longTitles.length,
    "Set a shorter `metaTitle` on these posts; the on-page <h1> can stay long.",
  );

  const shortTitles = posts.filter((p) => (p.metaTitle || p.title || "").trim().length < 15).map((p) => p.slug);
  r.check("onPage", "onpage.post.title_too_short", "medium", "Post titles are descriptive", "A very short title carries little keyword signal.", shortTitles);

  const noDescription = posts.filter((p) => !(p.metaDescription || p.excerpt || "").trim()).map((p) => p.slug);
  r.check(
    "onPage",
    "onpage.post.description",
    "high",
    "Every post has a description",
    "These posts fall back to the first words of the body as their snippet, which usually reads badly.",
    noDescription,
    noDescription.length,
    "Derive one from the opening paragraph: the audit engine can suggest per-post text, and the blog editor " +
      "accepts `metaDescription` directly.",
  );

  const badDescLength = posts
    .filter((p) => {
      const d = (p.metaDescription || p.excerpt || "").trim();
      return d.length > 0 && (d.length < 70 || d.length > 165);
    })
    .map((p) => `${p.slug} (${(p.metaDescription || p.excerpt).trim().length} chars)`);
  r.check(
    "onPage",
    "onpage.post.description_length",
    "low",
    "Descriptions are a usable length",
    "Under ~70 characters wastes the snippet; over ~165 is truncated.",
    badDescLength,
  );

  const dupTitles = duplicates(posts.map((p) => (p.metaTitle || p.title || "").trim().toLowerCase()));
  r.check(
    "onPage",
    "onpage.duplicate.title",
    "high",
    "Post titles are unique",
    "Identical titles make pages compete with each other for the same query, and look auto-generated.",
    dupTitles.map(([v, n]) => `"${v.slice(0, 60)}" ×${n}`),
    dupTitles.length,
  );

  const dupDescriptions = duplicates(
    posts.map((p) => (p.metaDescription || p.excerpt || "").trim().toLowerCase()).filter((d) => d.length > 0),
  );
  r.check(
    "onPage",
    "onpage.duplicate.description",
    "medium",
    "Post descriptions are unique",
    "Duplicated descriptions are a thin-content signal.",
    dupDescriptions.map(([v, n]) => `"${v.slice(0, 60)}" ×${n}`),
    dupDescriptions.length,
  );

  const badSlugs = posts.filter((p) => !isKebabSlug(p.slug)).map((p) => p.slug);
  r.check(
    "onPage",
    "onpage.slug.format",
    "low",
    "Slugs are lowercase and hyphenated",
    "Mixed case and underscores produce inconsistent, less readable URLs.",
    badSlugs,
  );

  const longSlugs = posts.filter((p) => p.slug.length > 75).map((p) => `${p.slug.slice(0, 50)}… (${p.slug.length})`);
  r.check("onPage", "onpage.slug.length", "low", "Slugs are a reasonable length", "Very long URLs are truncated in results and are harder to share.", longSlugs);

  const noH1 = posts.filter((p) => !headingLevels(p.content || "").includes(1)).map((p) => p.slug);
  // The edge Worker injects an <h1> into the noscript block, so this is about the
  // rendered article body, not the crawler's ability to find a heading at all.
  r.check(
    "onPage",
    "onpage.post.h1",
    "medium",
    "Post bodies contain an H1",
    "The article body has no top-level heading of its own, so the document outline depends entirely on the " +
      "injected one.",
    noH1,
  );

  const badOutline = posts
    .filter((p) => {
      const levels = headingLevels(p.content || "").filter((l) => l >= 2);
      const firstH3 = levels.indexOf(3);
      const firstH2 = levels.indexOf(2);
      return firstH3 !== -1 && (firstH2 === -1 || firstH3 < firstH2);
    })
    .map((p) => p.slug);
  r.check(
    "onPage",
    "onpage.post.heading_order",
    "low",
    "Heading levels are not skipped",
    "An H3 before any H2 breaks the outline assistive technology and crawlers rely on.",
    badOutline,
  );

  const noInternalLinks = posts.filter((p) => internalLinkCount(p.content || "", hostname) === 0).map((p) => p.slug);
  r.check(
    "onPage",
    "onpage.internal_links",
    "medium",
    "Posts link to other pages on the site",
    "Orphaned pages get less crawl attention and pass no authority onward. Internal linking is the cheapest " +
      "ranking lever available here.",
    noInternalLinks,
    noInternalLinks.length,
    "Add 2–3 contextual links per post to related posts in the same category.",
  );

  if (samplePost) {
    const canonical = canonicalOf(samplePost.body) || "";
    const doubled = /\/blog\/blog\//.test(canonical);
    r.check(
      "onPage",
      "onpage.post.canonical_shape",
      "critical",
      "Post canonical URLs point at a real route",
      "A canonical pointing at a path the app does not serve tells search engines the real page is a " +
        "duplicate of something that renders nothing.",
      doubled ? [canonical] : [],
    );
  }
}

// ---------------------------------------------------------------------------
// Category: Programmatic
// ---------------------------------------------------------------------------

function runProgrammatic(r: Report, x: { posts: any[]; samplePost: Probe | null }): void {
  const { posts, samplePost } = x;

  // Every post is reachable at BOTH /blog/<slug> and /<slug>. That is a
  // programmatic surface of ~4.5k pages with two URLs each, and canonical tags
  // are the only thing preventing it being duplicate content.
  r.check(
    "programmatic",
    "prog.dual_path.canonical",
    "critical",
    "Both URL shapes for a post resolve to one canonical",
    "Posts are served at /blog/<slug> and /<slug>. Without a canonical on both, that is ~2 duplicates per post.",
    samplePost && canonicalOf(samplePost.body) ? [] : ["/blog/<slug>"],
  );

  const dupSlugs = duplicates(posts.map((p) => p.slug.toLowerCase()));
  r.check(
    "programmatic",
    "prog.slug.unique",
    "critical",
    "Slugs are unique",
    "Two posts on one URL means one is unreachable and both look like duplicates.",
    dupSlugs.map(([v, n]) => `${v} ×${n}`),
    dupSlugs.length,
  );

  const thin = posts.filter((p) => wordCount(p.content || "") < 300).map((p) => `${p.slug} (${wordCount(p.content || "")} words)`);
  r.check(
    "programmatic",
    "prog.thin_content",
    "high",
    "Generated pages carry substantive content",
    "At scale, short near-identical pages are treated as thin/doorway content and can suppress the whole " +
      "section rather than just those pages.",
    thin,
    thin.length,
    "Expand or consolidate these. Merging several thin posts into one strong guide usually ranks better than " +
      "keeping them apart.",
  );

  const noCategory = posts.filter((p) => !(p.category || "").trim()).map((p) => p.slug);
  r.check(
    "programmatic",
    "prog.topic_cluster",
    "medium",
    "Posts are grouped into topic clusters",
    "Uncategorised posts cannot be linked into a hub-and-spoke cluster, which is how a large archive earns " +
      "topical authority instead of competing with itself.",
    noCategory,
  );
}

// ---------------------------------------------------------------------------
// Category: Content
// ---------------------------------------------------------------------------

function runContent(r: Report, x: { posts: any[] }): void {
  const { posts } = x;

  const veryThin = posts.filter((p) => wordCount(p.content || "") < 150).map((p) => p.slug);
  r.check(
    "content",
    "content.very_thin",
    "high",
    "No near-empty published posts",
    "Under ~150 words there is rarely enough to satisfy any query; these dilute the archive's quality signal.",
    veryThin,
  );

  const noExcerpt = posts.filter((p) => !(p.excerpt || "").trim()).map((p) => p.slug);
  r.check("content", "content.excerpt", "low", "Posts have an excerpt", "Used for listings, previews and as a description fallback.", noExcerpt);

  const TWO_YEARS = 730 * 24 * 60 * 60 * 1000;
  const stale = posts
    .filter((p) => {
      const ts = Number(p.updatedAt || p.publishedAt || 0);
      return ts > 0 && Date.now() - ts > TWO_YEARS;
    })
    .map((p) => p.slug);
  r.check(
    "content",
    "content.freshness",
    "medium",
    "Content has been reviewed recently",
    "Posts untouched for over two years — quiz answers and offer guides especially — go stale, and stale " +
      "pages lose rankings and erode trust when the information is wrong.",
    stale,
    stale.length,
    "Review the highest-traffic stale posts first; update or unpublish the ones that no longer apply.",
  );

  const noAuthor = posts.filter((p) => !(p.author || "").trim()).map((p) => p.slug);
  r.check(
    "content",
    "content.author",
    "medium",
    "Posts declare an author",
    "Authorship is a documented E-E-A-T signal and feeds Article schema.",
    noAuthor,
  );

  const noFaq = posts.filter((p) => !looksLikeFaq(p.content || "")).map((p) => p.slug);
  r.check(
    "content",
    "content.qa_sections",
    "low",
    "Posts include question-and-answer sections",
    "Q&A structure is what answer engines and AI search extract and cite. This is an opportunity count, not a defect.",
    noFaq,
    noFaq.length,
    "Add a short FAQ to the posts that already attract question queries; FAQPage schema then becomes eligible.",
  );
}

// ---------------------------------------------------------------------------
// Category: Image
// ---------------------------------------------------------------------------

function runImage(r: Report, x: { posts: any[] }): void {
  const { posts } = x;

  let missingAltTotal = 0;
  const postsMissingAlt: string[] = [];
  for (const p of posts) {
    const n = imagesMissingAlt(p.content || "");
    if (n > 0) {
      missingAltTotal += n;
      postsMissingAlt.push(`${p.slug} (${n} image${n === 1 ? "" : "s"})`);
    }
  }
  r.check(
    "image",
    "image.alt.missing",
    "high",
    "Every in-content image has ALT text",
    `${missingAltTotal} images across ${postsMissingAlt.length} posts have no ALT text. ALT is both an ` +
      "accessibility requirement and the only way an image can be understood by a crawler.",
    postsMissingAlt,
    postsMissingAlt.length,
    "ALT should describe what the image shows. For imported posts the surrounding heading is usually a good " +
      "starting point — but it must be reviewed, not bulk-filled with the post title, which is worse than empty.",
  );

  const noCover = posts.filter((p) => !(p.coverImageUrl || "").trim()).map((p) => p.slug);
  r.check(
    "image",
    "image.cover.missing",
    "medium",
    "Posts have a cover image",
    "The cover doubles as the og:image, so a post without one unfurls as a text-only link preview.",
    noCover,
  );

  const LEGACY_HOST = "tophunt-api.weadown-in.workers.dev";
  const legacy = posts
    .filter((p) => (p.coverImageUrl || "").includes(LEGACY_HOST) || (p.content || "").includes(LEGACY_HOST))
    .map((p) => p.slug);
  r.check(
    "image",
    "image.legacy_host",
    "low",
    "Stored image urls are on the media domain",
    "These posts still STORE the old Worker-proxied media host. Delivery is no longer affected — " +
      "routes/read.ts canonicalises cover and in-content urls onto the media domain on the way out, " +
      "so they are CDN-served and optimised — which is why this is low rather than medium. What " +
      "remains is data hygiene: the rewrite is per-response work, anything reading these columns " +
      "directly (exports, admin tools, D1 queries) still sees the old host, and the rewrite cannot " +
      "be retired until the stored values are canonical.",
    legacy,
    legacy.length,
    "Run apps/worker/scripts/media-domain-backfill.sql (PRODUCTION_DOMAINS.md §5).",
  );

  const rasterOnly = posts
    .filter((p) => /\.(jpe?g|png)(\?|$)/i.test(p.coverImageUrl || ""))
    .map((p) => p.slug);
  r.check(
    "image",
    "image.modern_format",
    "low",
    "Cover images can be served as WebP/AVIF",
    "JPEG/PNG originals are fine as sources, but they are only converted on the fly once Cloudflare " +
      "Transformations is enabled for the media zone.",
    rasterOnly,
    rasterOnly.length,
    'Enable Transformations on the tophunt.in zone and set MEDIA_TRANSFORMATIONS = "true" — ' +
      "lib/media.ts then emits format=auto variants with no client change.",
  );
}

// ---------------------------------------------------------------------------
// Category: AI Search / GEO
// ---------------------------------------------------------------------------

function runAiSearch(
  r: Report,
  x: { posts: any[]; routeProbes: Probe[]; samplePost: Probe | null },
): void {
  const { posts, routeProbes, samplePost } = x;
  const home = routeProbes.find((p) => p.path === "/");

  r.check(
    "aiSearch",
    "geo.organization_schema",
    "high",
    "Organization schema is published",
    "Answer engines use Organization to attribute claims to a named publisher. Without it the site is an " +
      "anonymous source and is less likely to be cited.",
    home && hasJsonLdType(home.body, "Organization") ? [] : ["/"],
  );

  r.check(
    "aiSearch",
    "geo.website_schema",
    "low",
    "WebSite schema is published",
    "Names the site as an entity and is a prerequisite for sitelinks.",
    home && hasJsonLdType(home.body, "WebSite") ? [] : ["/"],
  );

  r.check(
    "aiSearch",
    "geo.article_schema",
    "high",
    "Posts publish Article schema",
    "Article schema carries headline, date and publisher — the fields an answer engine needs to quote a page " +
      "with attribution.",
    samplePost && hasJsonLdType(samplePost.body, "Article") ? [] : ["/blog/<slug>"],
  );

  // SoftwareApplication is legitimate here — there is a real published mobile app.
  r.check(
    "aiSearch",
    "geo.softwareapplication_schema",
    "medium",
    "The mobile app is described with SoftwareApplication schema",
    "TopHunt ships a real Android/iOS app, so SoftwareApplication is applicable and is what surfaces app " +
      "details in AI answers about the product.",
    home && hasJsonLdType(home.body, "SoftwareApplication") ? [] : ["/"],
    home && hasJsonLdType(home.body, "SoftwareApplication") ? 0 : 1,
    "Add SoftwareApplication (name, operatingSystem, applicationCategory, installUrl) to the landing page " +
      "JSON-LD. Do NOT include aggregateRating unless real ratings are shown on the page — fabricated rating " +
      "markup is a manual-action risk.",
  );

  const faqEligible = posts.filter((p) => looksLikeFaq(p.content || ""));
  r.check(
    "aiSearch",
    "geo.faq_schema",
    "medium",
    "FAQ-shaped posts publish FAQPage schema",
    `${faqEligible.length} posts already read as question-and-answer content and are eligible for FAQPage ` +
      "schema, which is a direct citation surface for answer engines.",
    faqEligible.length ? faqEligible.map((p) => p.slug) : [],
    faqEligible.length,
    "Emit FAQPage only for posts whose Q&A pairs are genuinely visible on the page — marking up questions " +
      "that a user cannot see is misleading structured data.",
  );

  const noAuthorInfo = posts.filter((p) => !(p.author || "").trim()).map((p) => p.slug);
  r.check(
    "aiSearch",
    "geo.author_signal",
    "medium",
    "Posts carry author information",
    "Author attribution is an explicit E-E-A-T signal and is required for Article schema to be complete.",
    noAuthorInfo,
  );

  const noNoscript = samplePost && !/<noscript>/i.test(samplePost.body);
  r.check(
    "aiSearch",
    "geo.crawlable_without_js",
    "high",
    "Post content is readable without JavaScript",
    "This is a client-rendered SPA. Most AI crawlers and every social scraper read only the initial HTML, " +
      "so content that exists solely after hydration is invisible to them.",
    noNoscript ? ["/blog/<slug>"] : [],
  );
}

// ---------------------------------------------------------------------------
// Category: Local
// ---------------------------------------------------------------------------

function runLocal(r: Report, x: { routeProbes: Probe[] }): void {
  const home = x.routeProbes.find((p) => p.path === "/");

  const langOk = home ? /<html[^>]*\blang\s*=\s*["'][a-z]{2}(-[A-Za-z]{2})?["']/i.test(home.body) : false;
  r.check(
    "local",
    "local.lang_attribute",
    "medium",
    "Pages declare a language",
    "`<html lang>` tells search engines which language and region the content targets.",
    langOk ? [] : ["/"],
    langOk ? 0 : 1,
    'Set lang="en-IN" on the document to state the India-English target explicitly.',
  );

  r.check(
    "local",
    "local.organization_contact",
    "medium",
    "Organisation contact details are published",
    "A reachable contact address is a trust signal for both search engines and users, and is what makes " +
      "Organization schema useful rather than decorative.",
    home && /(support|contact|ops)@tophunt\.in/i.test(home.body) ? [] : ["/"],
    home && /(support|contact|ops)@tophunt\.in/i.test(home.body) ? 0 : 1,
    "Publish a contact email in the Organization JSON-LD and on a reachable contact/support page.",
  );
}

// ---------------------------------------------------------------------------
// util
// ---------------------------------------------------------------------------

/** Values appearing more than once, as [value, count], most frequent first. */
function duplicates(values: string[]): [string, number][] {
  const counts = new Map<string, number>();
  for (const v of values) {
    if (!v) continue;
    counts.set(v, (counts.get(v) ?? 0) + 1);
  }
  return [...counts.entries()].filter(([, n]) => n > 1).sort((a, b) => b[1] - a[1]);
}
