import { Model } from '@nozbe/watermelondb';
import { field, date, readonly } from '@nozbe/watermelondb/decorators';

export type PendingActionType = 'view' | 'reaction' | 'create' | 'delete';

export interface PendingActionData {
  storyId?: string;
  emoji?: string;
  userId?: string;
  [key: string]: any;
}

export class PendingActionModel extends Model {
  static table = 'pending_actions';

  // `id` is inherited from Model and generated by WatermelonDB. Do not
  // redeclare it — see the note in StoryModel.
  @field('type') type!: PendingActionType;
  @field('story_id') storyId!: string;
  @field('user_id') userId!: string;
  @field('data') data!: string; // JSON string of PendingActionData

  // `number` is NOT exported by watermelondb/decorators; numeric columns use
  // @field like everything else.
  @field('timestamp') timestamp!: number;
  @field('retries') retries!: number;

  // Auto-touched by WatermelonDB on every write. Do not assign manually.
  @readonly @date('updated_at') updatedAt!: Date;

  getData(): PendingActionData {
    if (!this.data) return {};
    try {
      const parsed = JSON.parse(this.data);
      return parsed && typeof parsed === 'object' ? parsed : {};
    } catch {
      return {};
    }
  }
}
