name: Deploy Firebase Functions - Production

on:
  push:
    branches:
      - main
    paths:
      - 'apps/functions/**'
      - '.github/workflows/firebase-functions-production.yml'

jobs:
  deploy_firebase_prod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@vv3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install function dependencies
        working-directory: ./apps/functions
        run: npm install

      - name: Deploy to Firebase Production
        working-directory: ./apps/functions
        run: firebase deploy --only functions --project ${{ secrets.FIREBASE_PROD_PROJECT_ID }} --token ${{ secrets.FIREBASE_TOKEN }}
