name: Deploy Firebase Functions - Staging

on:
  push:
    branches:
      - develop
    paths:
      - 'apps/functions/**'
      - '.github/workflows/firebase-functions-staging.yml'

jobs:
  deploy_firebase_staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install function dependencies
        working-directory: ./apps/functions
        run: npm install

      - name: Deploy to Firebase Staging
        working-directory: ./apps/functions
        run: firebase deploy --only functions --project ${{ secrets.FIREBASE_STAGING_PROJECT_ID }} --token ${{ secrets.FIREBASE_TOKEN }}
